shallow_clone: true

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2 --compat none"
  - LUA: "lua 5.3 --compat none"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.1"

# Abuse this section so we can have a matrix with different Compiler versions
configuration:
  - mingw
  - vs_32
  - vs_64

install:
  - set PATH=%CD%\env\bin;C:\Python27\Scripts;C:\MinGW\bin;%PATH%
  - pip install hererocks
  - hererocks env --%LUA% --target %configuration%

before_build:

build_script:
- cmake .
- cmake --build . --config Release

before_test:

test_script:

after_test: